spring:
  application:
    name: eureka-client


server:
  port: 30000
eureka:
  client:
    service-url:
      defaultZone: "http://peer2:20000/eureka/,http://peer1:20001/eureka/"
#      defaultZone: "http://localhost:20000/eureka/"
  instance:
    lease-renewal-interval-in-seconds: 5 #每隔5秒钟，向服务中兴发送一条续约指令
    lease-expiration-duration-in-seconds: 30 #如果30秒内，依然没有收到续约请求，判定服务过期



